language:
  - php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

before_script:
  - mkdir build
  - phpenv config-add tests/php.ini
  - mysql -e "create database IF NOT EXISTS tipsy;" -uroot;
  - composer self-update
  - composer install

script:
  - phpunit --configuration tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v